language: ruby
before_install: "gem install bundler --pre"
bundler_args: "--without development --deployment --jobs 2"
before_script:
  - "psql -c 'create database ocn_test;' -U postgres"
  - "cp config/database.yml{.travis,} "
script: "bundle exec rake spec"
cache: bundler
rvm:
  - 2.0.0
